openapi: 3.0.3
info:
  title: Argilla v1 Authentication vectors-settings API
  description: Argilla Server API v1
  version: 2.8.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    email: contact@argilla.io
    url: https://argilla.io
servers:
- url: https://argilla.io/api/v1
  description: Argilla REST API v1
tags:
- name: vectors-settings
paths:
  /vectors-settings/{vector_settings_id}:
    patch:
      tags:
      - vectors-settings
      summary: Update Vector Settings
      operationId: update_vector_settings_vectors_settings__vector_settings_id__patch
      security:
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: vector_settings_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Vector Settings Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VectorSettingsUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VectorSettings'
        '400':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::MissingDatasetRecordsError
                  params:
                    extra: error parameters
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityNotFoundError
                  params:
                    extra: error parameters
          description: Not Found
        '403':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ForbiddenOperationError
                  params:
                    extra: error parameters
          description: Forbidden
        '409':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityAlreadyExistsError
                  params:
                    extra: error parameters
          description: Conflict
        '422':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ValidationError
                  params:
                    extra: error parameters
          description: Unprocessable Content
        '500':
          content:
            application/json:
              example:
                detail:
                  code: builtins.TypeError
          description: Internal Server Error
    delete:
      tags:
      - vectors-settings
      summary: Delete Vector Settings
      operationId: delete_vector_settings_vectors_settings__vector_settings_id__delete
      security:
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: vector_settings_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Vector Settings Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VectorSettings'
        '400':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::MissingDatasetRecordsError
                  params:
                    extra: error parameters
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityNotFoundError
                  params:
                    extra: error parameters
          description: Not Found
        '403':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ForbiddenOperationError
                  params:
                    extra: error parameters
          description: Forbidden
        '409':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityAlreadyExistsError
                  params:
                    extra: error parameters
          description: Conflict
        '422':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ValidationError
                  params:
                    extra: error parameters
          description: Unprocessable Content
        '500':
          content:
            application/json:
              example:
                detail:
                  code: builtins.TypeError
          description: Internal Server Error
components:
  schemas:
    VectorSettings:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
        title:
          type: string
          title: Title
        dimensions:
          type: integer
          title: Dimensions
        dataset_id:
          type: string
          format: uuid
          title: Dataset Id
        inserted_at:
          type: string
          format: date-time
          title: Inserted At
        updated_at:
          type: string
          format: date-time
          title: Updated At
      type: object
      required:
      - id
      - name
      - title
      - dimensions
      - dataset_id
      - inserted_at
      - updated_at
      title: VectorSettings
    VectorSettingsUpdate:
      properties:
        title:
          title: Title
          type: string
          maxLength: 500
          minLength: 1
          description: The title of the vector settings
          nullable: true
      type: object
      required:
      - title
      title: VectorSettingsUpdate
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-Argilla-Api-Key
    HTTPBearer:
      type: http
      scheme: bearer
