openapi: 3.0.3
info:
  title: Argilla v1 Authentication settings API
  description: Argilla Server API v1
  version: 2.8.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    email: contact@argilla.io
    url: https://argilla.io
servers:
- url: https://argilla.io/api/v1
  description: Argilla REST API v1
tags:
- name: settings
paths:
  /settings:
    get:
      tags:
      - settings
      summary: Get Settings
      operationId: get_settings_settings_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::MissingDatasetRecordsError
                  params:
                    extra: error parameters
        '404':
          description: Not Found
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityNotFoundError
                  params:
                    extra: error parameters
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ForbiddenOperationError
                  params:
                    extra: error parameters
        '409':
          description: Conflict
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityAlreadyExistsError
                  params:
                    extra: error parameters
        '422':
          description: Unprocessable Content
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ValidationError
                  params:
                    extra: error parameters
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                detail:
                  code: builtins.TypeError
components:
  schemas:
    ArgillaSettings:
      properties:
        show_huggingface_space_persistent_storage_warning:
          title: Show Huggingface Space Persistent Storage Warning
          type: boolean
          nullable: true
        share_your_progress_enabled:
          type: boolean
          title: Share Your Progress Enabled
          default: false
      type: object
      title: ArgillaSettings
    HuggingfaceSettings:
      properties:
        space_id:
          title: Space Id
          type: string
          nullable: true
        space_title:
          title: Space Title
          type: string
          nullable: true
        space_subdomain:
          title: Space Subdomain
          type: string
          nullable: true
        space_host:
          title: Space Host
          type: string
          nullable: true
        space_repo_name:
          title: Space Repo Name
          type: string
          nullable: true
        space_author_name:
          title: Space Author Name
          type: string
          nullable: true
        space_persistent_storage_enabled:
          type: boolean
          title: Space Persistent Storage Enabled
      type: object
      required:
      - space_id
      - space_title
      - space_subdomain
      - space_host
      - space_repo_name
      - space_author_name
      - space_persistent_storage_enabled
      title: HuggingfaceSettings
    Settings:
      properties:
        argilla:
          $ref: '#/components/schemas/ArgillaSettings'
        huggingface:
          $ref: '#/components/schemas/HuggingfaceSettings'
          nullable: true
      type: object
      required:
      - argilla
      title: Settings
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-Argilla-Api-Key
    HTTPBearer:
      type: http
      scheme: bearer
