openapi: 3.0.3
info:
  title: Argilla v1 Authentication metadata properties API
  description: Argilla Server API v1
  version: 2.8.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    email: contact@argilla.io
    url: https://argilla.io
servers:
- url: https://argilla.io/api/v1
  description: Argilla REST API v1
tags:
- name: metadata properties
paths:
  /metadata-properties/{metadata_property_id}/metrics:
    get:
      tags:
      - metadata properties
      summary: Get Metadata Property Metrics
      operationId: get_metadata_property_metrics_metadata_properties__metadata_property_id__metrics_get
      security:
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: metadata_property_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Metadata Property Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/TermsMetadataMetrics'
                - $ref: '#/components/schemas/IntegerMetadataMetrics'
                - $ref: '#/components/schemas/FloatMetadataMetrics'
                discriminator:
                  propertyName: type
                  mapping:
                    terms: '#/components/schemas/TermsMetadataMetrics'
                    integer: '#/components/schemas/IntegerMetadataMetrics'
                    float: '#/components/schemas/FloatMetadataMetrics'
                title: Response Get Metadata Property Metrics Metadata Properties  Metadata Property Id  Metrics Get
        '400':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::MissingDatasetRecordsError
                  params:
                    extra: error parameters
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityNotFoundError
                  params:
                    extra: error parameters
          description: Not Found
        '403':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ForbiddenOperationError
                  params:
                    extra: error parameters
          description: Forbidden
        '409':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityAlreadyExistsError
                  params:
                    extra: error parameters
          description: Conflict
        '422':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ValidationError
                  params:
                    extra: error parameters
          description: Unprocessable Content
        '500':
          content:
            application/json:
              example:
                detail:
                  code: builtins.TypeError
          description: Internal Server Error
  /metadata-properties/{metadata_property_id}:
    patch:
      tags:
      - metadata properties
      summary: Update Metadata Property
      operationId: update_metadata_property_metadata_properties__metadata_property_id__patch
      security:
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: metadata_property_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Metadata Property Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetadataPropertyUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataProperty'
        '400':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::MissingDatasetRecordsError
                  params:
                    extra: error parameters
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityNotFoundError
                  params:
                    extra: error parameters
          description: Not Found
        '403':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ForbiddenOperationError
                  params:
                    extra: error parameters
          description: Forbidden
        '409':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityAlreadyExistsError
                  params:
                    extra: error parameters
          description: Conflict
        '422':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ValidationError
                  params:
                    extra: error parameters
          description: Unprocessable Content
        '500':
          content:
            application/json:
              example:
                detail:
                  code: builtins.TypeError
          description: Internal Server Error
    delete:
      tags:
      - metadata properties
      summary: Delete Metadata Property
      operationId: delete_metadata_property_metadata_properties__metadata_property_id__delete
      security:
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: metadata_property_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Metadata Property Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataProperty'
        '400':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::MissingDatasetRecordsError
                  params:
                    extra: error parameters
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityNotFoundError
                  params:
                    extra: error parameters
          description: Not Found
        '403':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ForbiddenOperationError
                  params:
                    extra: error parameters
          description: Forbidden
        '409':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::EntityAlreadyExistsError
                  params:
                    extra: error parameters
          description: Conflict
        '422':
          content:
            application/json:
              example:
                detail:
                  code: argilla.api.errors::ValidationError
                  params:
                    extra: error parameters
          description: Unprocessable Content
        '500':
          content:
            application/json:
              example:
                detail:
                  code: builtins.TypeError
          description: Internal Server Error
components:
  schemas:
    MetadataPropertyUpdate:
      properties:
        title:
          title: Title
          type: string
          maxLength: 500
          minLength: 1
          description: The title of the metadata property
          nullable: true
        visible_for_annotators:
          title: Visible For Annotators
          type: boolean
          nullable: true
      type: object
      title: MetadataPropertyUpdate
    TermsMetadataProperty:
      properties:
        type:
          type: string
          enum:
          - terms
          const: terms
          title: Type
        values:
          title: Values
          items: {}
          type: array
          nullable: true
      type: object
      required:
      - type
      title: TermsMetadataProperty
    IntegerMetadataMetrics:
      properties:
        min:
          title: Min
          type: integer
          nullable: true
        max:
          title: Max
          type: integer
          nullable: true
        type:
          type: string
          enum:
          - integer
          const: integer
          title: Type
          default: integer
      type: object
      title: IntegerMetadataMetrics
    FloatMetadataMetrics:
      properties:
        min:
          title: Min
          type: number
          nullable: true
        max:
          title: Max
          type: number
          nullable: true
        type:
          type: string
          enum:
          - float
          const: float
          title: Type
          default: float
      type: object
      title: FloatMetadataMetrics
    TermsMetadataMetrics:
      properties:
        type:
          type: string
          enum:
          - terms
          const: terms
          title: Type
          default: terms
        total:
          type: integer
          title: Total
        values:
          items:
            $ref: '#/components/schemas/TermCount'
          type: array
          title: Values
      type: object
      required:
      - total
      title: TermsMetadataMetrics
    FloatMetadataProperty:
      properties:
        type:
          type: string
          enum:
          - float
          const: float
          title: Type
        min:
          title: Min
          type: number
          nullable: true
        max:
          title: Max
          type: number
          nullable: true
      type: object
      required:
      - type
      title: FloatMetadataProperty
    MetadataProperty:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
        title:
          type: string
          title: Title
        settings:
          oneOf:
          - $ref: '#/components/schemas/TermsMetadataProperty'
          - $ref: '#/components/schemas/IntegerMetadataProperty'
          - $ref: '#/components/schemas/FloatMetadataProperty'
          title: Settings
          discriminator:
            propertyName: type
            mapping:
              float: '#/components/schemas/FloatMetadataProperty'
              integer: '#/components/schemas/IntegerMetadataProperty'
              terms: '#/components/schemas/TermsMetadataProperty'
        visible_for_annotators:
          type: boolean
          title: Visible For Annotators
        dataset_id:
          type: string
          format: uuid
          title: Dataset Id
        inserted_at:
          type: string
          format: date-time
          title: Inserted At
        updated_at:
          type: string
          format: date-time
          title: Updated At
      type: object
      required:
      - id
      - name
      - title
      - settings
      - visible_for_annotators
      - dataset_id
      - inserted_at
      - updated_at
      title: MetadataProperty
    TermCount:
      properties:
        term:
          title: Term
        count:
          type: integer
          title: Count
      type: object
      required:
      - term
      - count
      title: TermCount
    IntegerMetadataProperty:
      properties:
        type:
          type: string
          enum:
          - integer
          const: integer
          title: Type
        min:
          title: Min
          type: integer
          nullable: true
        max:
          title: Max
          type: integer
          nullable: true
      type: object
      required:
      - type
      title: IntegerMetadataProperty
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-Argilla-Api-Key
    HTTPBearer:
      type: http
      scheme: bearer
